Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -11,7 +11,6 @@ on:
 
 jobs:
   build-java:
-
     runs-on: ubuntu-latest
     
     steps:
@@ -28,13 +27,20 @@ jobs:
     - name: Build with Gradle
       run: ./gradlew build
 
-    - name: List build/libs directory
-      run: ls -la build/libs
+    - name: Verify JAR file
+      run: |
+        echo "Checking build/libs directory..."
+        ls -la build/libs
+        if [ ! -f build/libs/my-app-1.0-SNAPSHOT.jar ]; then
+          echo "JAR file not found!"
+          exit 1
+        fi
 
     - name: Build and Push Docker Image
       uses: mr-smithers-excellent/docker-build-push@v4
       with:
         image: technosport/test01
+        tags: ${{ github.sha }}
         registry: docker.io
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
